const { test } = require('node:test');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.ENHANCENCM_PLAYWRIGHT || 'playwright');
const { createServer } = require('../tools/preview-music');
test('Spotify global search, current queue and song context actions', async () => {
  const server = createServer(); await new Promise(r => server.listen(0, '127.0.0.1', r));
  const browser = await chromium.launch({headless:true, executablePath:process.env.ENHANCENCM_CHROMIUM});
  const page = await browser.newPage({viewport:{width:1440,height:900}}), errors=[];
  page.on('pageerror', e => errors.push(e.message));
  try {
    await page.goto(`http://127.0.0.1:${server.address().port}/`);
    await page.locator('#albums button').first().waitFor();
    assert.equal(await page.locator('#albums small').count(),0);
    assert.equal(await page.locator('#search').isVisible(),true);
    await page.locator('[data-view="songs"]').click();
    assert.equal(await page.locator('#tracks tr').count(),0);
    await page.locator('[data-view="discover"]').click();
    await page.evaluate(() => {
      window.searchCalls=[]; window.mutations=[];
      EnhanceNCM.sdk.songs.search=async (keyword,opts) => {
        searchCalls.push([keyword,opts.offset]);
        if(keyword==='失败') throw Error('failed');
        return {items:[{id:1001+opts.offset,name:keyword+' result',ar:[{name:'artist'}]}],total:2,more:opts.offset===0};
      };
      EnhanceNCM.sdk.playlists.addTrack=async (id,song) => mutations.push(['add',String(id),song]);
      EnhanceNCM.sdk.playlists.removeTrack=async (id,song) => mutations.push(['remove',String(id),song]);
    });
    await page.locator('#search').fill('全站'); await page.locator('#search').press('Enter');
    await page.locator('#tracks [data-play="1001"]').waitFor();
    await page.locator('#more-search').click(); await page.locator('#tracks [data-play="1002"]').waitFor();
    assert.deepEqual(await page.evaluate(()=>searchCalls),[['全站',0],['全站',1]]);
    await page.locator('#tracks [data-play="1001"]').click();
    await page.locator('#tracks [data-play="1002"]').click({button:'right'});
    await page.locator('[data-song-action="next"]').click();
    assert.equal(await page.locator('#now-title').textContent(),'全站 result');
    await page.locator('[data-view="songs"]').click();
    assert.equal(await page.locator('#tracks tr').count(),2);
    await page.locator('#tracks tr').first().click({button:'right'});
    await page.locator('[data-song-action="add"]').click();
    await page.locator('[data-add-track="501"]').click();
    await page.locator('#add-track-status').filter({hasText:'已添加'}).waitFor();
    assert.deepEqual(await page.evaluate(()=>mutations[0]),['add','501',1001]);
    await page.evaluate(()=>{ EnhanceNCM.sdk.playlists.addTrack=async()=>{ throw Object.assign(Error('denied'),{code:'403'}); }; });
    await page.locator('[data-add-track="501"]').click();
    await page.locator('#add-track-status').filter({hasText:'添加失败'}).waitFor();
    assert.equal(await page.locator('[data-add-track="501"]').isEnabled(),true);
    await page.locator('#close-add-track').click();
    await page.locator('#sidebar-created [data-playlist="501"]').click();
    await page.locator('#tracks [data-play="3"]').waitFor();
    await page.locator('#tracks tr').first().click({button:'right'});
    await page.locator('[data-song-action="remove"]').click();
    await page.waitForFunction(()=>mutations.some(x=>x[0]==='remove'));
    await page.evaluate(()=>EnhanceNCM._player.getActiveSession().append(Array.from({length:120},(_,i)=>({id:2000+i,name:'Queue '+i}))));
    await page.locator('#queue-toggle').click();
    assert.equal(await page.locator('#queue-tracks button').count(),100);
    await page.locator('[data-view="songs"]').click();
    assert.equal(Number(await page.locator('#tracks').getAttribute('data-total')),122);
    assert.ok(await page.locator('#tracks [data-song]').count() <= 80);
    await page.screenshot({path:'out/spotify-song-actions.png'});
    await page.locator('[data-view="discover"]').click();
    await page.locator('#search').fill('失败'); await page.locator('#search').press('Enter');
    await page.locator('#list-detail').filter({hasText:'搜索失败'}).waitFor();
    await page.evaluate(()=>{ EnhanceNCM.sdk.songs.search=()=>new Promise(resolve=>{window.finishSearch=resolve;}); });
    await page.locator('#search').fill('延迟'); await page.locator('#search').press('Enter');
    await page.waitForFunction(()=>!!window.finishSearch);
    await page.locator('[data-view="songs"]').click();
    await page.evaluate(()=>finishSearch({items:[{id:9999,name:'过期'}],total:1,more:false}));
    assert.equal(await page.locator('#list-heading').textContent(),'当前歌曲列表');
    assert.equal(await page.locator('#tracks [data-play="9999"]').count(),0);
    assert.deepEqual(errors,[]);
  } finally { await browser.close(); await new Promise(r=>server.close(r)); }
});
