import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import svgr from 'vite-plugin-svgr';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const result = await build({
  configFile: false,
  root,
  logLevel: 'warn',
  plugins: [svgr({ svgrOptions: { ref: true } })],
  resolve: { alias: Object.fromEntries(['core', 'react', 'react-full'].map(name =>
    [`@applemusic-like-lyrics/${name}`, path.join(root, `third_party/amll/${name}/src/index.ts`)])) },
  css: { transformer: 'lightningcss' },
  define: { 'process.env.NODE_ENV': JSON.stringify('production') },
  build: {
    write: false,
    // The shipped CloudMusic CEF is Chromium 91 (libcef 91.0.4472.169).
    // Keep this target in sync: newer targets leave class static blocks in
    // the bundle, which CEF 91 rejects as `Unexpected token '{'`.
    target: 'chrome91',
    cssMinify: 'lightningcss',
    lib: { entry: path.join(root, 'src/themes/amll/main.tsx'), name: 'AMLLTheme', formats: ['iife'] },
  },
});
const outputs = (Array.isArray(result) ? result : [result]).flatMap(item => item.output);
const css = outputs.filter(item => item.type === 'asset' && item.fileName.endsWith('.css')).map(item => item.source).join('\n');
const js = outputs.filter(item => item.type === 'chunk').map(item => item.code).join('\n');
const source = '// AMLL UI: GPL-3.0; see LICENSE and NOTICE.md. Generated by tools/build-amll.mjs.\n' +
  '(function(){const __AMLL_CSS__ = ' + JSON.stringify(css) + ';\n' + js + '\n})();\n';
// The CSS string legitimately contains selectors such as `position:static{}`.
// Check the JavaScript portion separately so a future dependency upgrade cannot
// reintroduce syntax that Chromium 91 cannot parse.
const cssBoundary = source.indexOf('";\n', source.indexOf('__AMLL_CSS__'));
const runtimeSource = cssBoundary < 0 ? source : source.slice(cssBoundary + 3);
if (/\bstatic\s*\{/.test(runtimeSource)) throw Error('AMLL contains class static blocks unsupported by Chromium 91');
// Match module declarations at a statement boundary. A dependency used by
// Radix contains the prose string "import the right car"; the old word-boundary
// check treated that harmless string as unbundled ESM after Dialog was added.
if (/(?:^|[;\n])\s*(?:import|export)\s/m.test(runtimeSource)) throw Error('AMLL bundle unexpectedly contains ES module syntax');
if (Buffer.byteLength(source) > 8 * 1024 * 1024) throw Error('AMLL exceeds the host 8 MiB theme limit');
const output = path.join(root, 'build/EnhanceNCM/Themes/AMLL');
fs.mkdirSync(output, { recursive: true });
fs.writeFileSync(path.join(output, 'theme.js'), source);
for (const name of ['LICENSE', 'NOTICE.md']) fs.copyFileSync(path.join(root, 'third_party/amll', name), path.join(output, name));
console.log('AMLL theme built (' + (Buffer.byteLength(source) / 1024).toFixed(0) + ' KiB)');
