const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.join(__dirname, "..");
const sdkSources = [
  "src/sdk/startup.js",
  "src/sdk/settings.js",
  "src/sdk/transport/native.js",
  "src/sdk/transport/desktop.js",
  "src/sdk/domain/lyrics.js",
  "src/sdk/domain/local-music.js",
  "src/sdk/domain/audio-source.js",
  "src/sdk/domain/playback.js",
  "src/sdk/domain/shell.js",
  "src/sdk/domain/library-cache.js",
  "src/sdk/domain/player-session.js",
  "src/sdk/domain/player-persistence.js",
  "src/sdk/domain/presentation.js",
  "src/sdk/domain/cover-colors.js",
  "src/sdk/domain/music.js",
];
const hostSources = ["src/host/app.js", "src/host/entry.js", "src/host/themes.js", "src/host/ui/switcher.js",
  "src/host/ui/tray-menu.js", "src/host/local-files.js", "src/host/theme-host.js"];
const themeSources = ["src/themes/spotify/music-styles.js", "src/themes/spotify/standalone.js"];
const buildRoot = path.join(projectRoot, "build");
const output = path.join(buildRoot, "EnhanceNCM-page.js");
const sdkOutput = path.join(buildRoot, "EnhanceNCM-sdk.js");
const themeOutput = path.join(buildRoot, "EnhanceNCM/Spotify/theme.js");
function join(files) {
  return "// Generated by tools/build-page.js; edit the source modules instead.\n" +
    files.map(file => fs.readFileSync(path.join(projectRoot, file), "utf8").trimEnd()).join("\n\n") + "\n";
}
function sdkBundle() { return join(sdkSources); }
function hostBundle() { return join(hostSources); }
function themeBundle() { return join(themeSources); }
// In-memory integration fixture. Production always deploys the three separate files.
function bundle() {
  return sdkBundle() + "\nEnhanceNCM._themeCatalog = " + JSON.stringify([
    { id: "spotify", name: "Spotify", source: themeBundle() }
  ]) + ";\n" + hostBundle();
}
function build() {
  for (const [file, source] of [[sdkOutput, sdkBundle()], [output, hostBundle()], [themeOutput, themeBundle()]]) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== source) fs.writeFileSync(file, source);
  }
}
if (require.main === module) build();
module.exports = { sdkSources, hostSources, themeSources, buildRoot, bundle, output, sdkOutput, themeOutput, sdkBundle, hostBundle, themeBundle, build };
