const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const crypto = require("node:crypto");

const projectRoot = path.join(__dirname, "..");
const sdkSources = [
  "src/sdk/startup.js",
  "src/sdk/settings.js",
  "src/sdk/transport/native.js",
  "src/sdk/transport/desktop.js",
  "src/sdk/domain/lyrics.js",
  "src/sdk/domain/local-music.js",
  "src/sdk/domain/audio-source.js",
  "src/sdk/domain/playback.js",
  "src/sdk/domain/shell.js",
  "src/sdk/domain/library-cache.js",
  "src/sdk/domain/player-session.js",
  "src/sdk/domain/now-playing.js",
  "src/sdk/domain/player-persistence.js",
  "src/sdk/domain/presentation.js",
  "src/sdk/domain/cover-colors.js",
  "src/sdk/domain/music.js",
];
const hostSources = ["src/host/app.js", "src/host/entry.js", "src/host/themes.js", "src/host/ui/switcher.js",
  "src/host/ui/tray-menu.js", "src/host/local-files.js", "src/host/theme-host.js"];
const themeSources = ["src/themes/spotify/music-styles.js", "src/themes/spotify/standalone.js"];
const buildRoot = path.join(projectRoot, "build");
const runtimeRoot = path.join(buildRoot, "EnhanceNCM");
const themesRoot = path.join(runtimeRoot, "Themes");
const output = path.join(runtimeRoot, "EnhanceNCM-page.js");
const sdkOutput = path.join(runtimeRoot, "EnhanceNCM-sdk.js");
const themeOutput = path.join(themesRoot, "Spotify/theme.js");
const amllOutput = path.join(themesRoot, "AMLL/theme.js");
function buildAMLL() {
  const hash = crypto.createHash('sha256');
  function add(file) {
    if (fs.statSync(file).isDirectory()) {
      for (const entry of fs.readdirSync(file).sort()) add(path.join(file, entry));
    } else hash.update(fs.readFileSync(file));
  }
  for (const name of ['src/themes/amll', 'third_party/amll', 'tools/build-amll.mjs', 'package-lock.json']) add(path.join(projectRoot, name));
  const stamp = path.join(buildRoot, 'amll-build.sha256'), digest = hash.digest('hex');
  if (fs.existsSync(amllOutput) && ['LICENSE', 'NOTICE.md'].every(name => fs.existsSync(path.join(path.dirname(amllOutput), name))) && fs.existsSync(stamp) && fs.readFileSync(stamp, 'utf8') === digest) return;
  const result = spawnSync(process.execPath, [path.join(__dirname, 'build-amll.mjs')], { cwd: projectRoot, stdio: 'inherit' });
  if (result.error) throw result.error;
  if (result.status !== 0) throw Error('AMLL theme build failed; run npm ci to install its dependencies.');
  fs.writeFileSync(stamp, digest);
}
function join(files) {
  return "// Generated by tools/build-page.js; edit the source modules instead.\n" +
    files.map(file => fs.readFileSync(path.join(projectRoot, file), "utf8").trimEnd()).join("\n\n") + "\n";
}
function sdkBundle() { return join(sdkSources); }
function hostBundle() { return join(hostSources); }
function themeBundle() { return join(themeSources); }
// In-memory integration fixture. Production always deploys the three separate files.
function bundle() {
  return sdkBundle() + "\nEnhanceNCM._themeCatalog = " + JSON.stringify([
    { id: "spotify", name: "Spotify", source: themeBundle() }
  ]) + ";\n" + hostBundle();
}
function build() {
  for (const [file, source] of [[sdkOutput, sdkBundle()], [output, hostBundle()], [themeOutput, themeBundle()]]) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== source) fs.writeFileSync(file, source);
  }
  buildAMLL();
}
if (require.main === module) build();
module.exports = { sdkSources, hostSources, themeSources, buildRoot, runtimeRoot, themesRoot, bundle, output, sdkOutput, themeOutput, amllOutput, sdkBundle, hostBundle, themeBundle, build };
